name: Compile CkOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: chmod
      run: chmod +x scripts/*.sh
    - name: installpkg
      run: sh -c "sudo apt update; sudo apt install nasm xorriso clang lld qemu-system-x86"
    - name: make
      run: sh -c "make cl; make -j$(nproc)"
    - name: quicktest
      run: ! timeout --preserve-status -s 2 30s qemu-system-i386 -cdrom build/boot.iso -nographic -boot order=dca
